create schema if not exists private;
create or replace function private.is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organization_members om where om.organization_id=target_org and om.user_id=(select auth.uid())); $$;
create or replace function private.has_org_role(target_org uuid,allowed_roles public.organization_role[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organization_members om where om.organization_id=target_org and om.user_id=(select auth.uid()) and om.role=any(allowed_roles)); $$;
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,display_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name',new.raw_user_meta_data->>'full_name')) on conflict(id) do update set email=excluded.email; return new; end; $$;
drop policy organizations_select_member on public.organizations;
create policy organizations_select_member on public.organizations for select to authenticated using (private.is_org_member(id));
drop policy organizations_update_admin on public.organizations;
create policy organizations_update_admin on public.organizations for update to authenticated using (private.has_org_role(id,array['owner','admin']::public.organization_role[])) with check (private.has_org_role(id,array['owner','admin']::public.organization_role[]));
drop policy organization_members_select_member on public.organization_members;
create policy organization_members_select_member on public.organization_members for select to authenticated using (private.is_org_member(organization_id));
drop policy organization_members_insert_admin on public.organization_members;
create policy organization_members_insert_admin on public.organization_members for insert to authenticated with check (((select auth.uid())=user_id and role='owner') or private.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
drop policy organization_members_update_admin on public.organization_members;
create policy organization_members_update_admin on public.organization_members for update to authenticated using (private.has_org_role(organization_id,array['owner','admin']::public.organization_role[])) with check (private.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
drop policy organization_members_delete_admin on public.organization_members;
create policy organization_members_delete_admin on public.organization_members for delete to authenticated using (private.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
drop policy units_select_member on public.units;
create policy units_select_member on public.units for select to authenticated using (private.is_org_member(organization_id));
drop policy units_insert_manager on public.units;
create policy units_insert_manager on public.units for insert to authenticated with check (private.has_org_role(organization_id,array['owner','admin','manager']::public.organization_role[]));
drop policy units_update_manager on public.units;
create policy units_update_manager on public.units for update to authenticated using (private.has_org_role(organization_id,array['owner','admin','manager']::public.organization_role[])) with check (private.has_org_role(organization_id,array['owner','admin','manager']::public.organization_role[]));
drop policy units_delete_admin on public.units;
create policy units_delete_admin on public.units for delete to authenticated using (private.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
drop policy meters_select_member on public.meters;
create policy meters_select_member on public.meters for select to authenticated using (exists(select 1 from public.units u where u.id=unit_id and private.is_org_member(u.organization_id)));
drop policy meters_insert_manager on public.meters;
create policy meters_insert_manager on public.meters for insert to authenticated with check (exists(select 1 from public.units u where u.id=unit_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[])));
drop policy meters_update_manager on public.meters;
create policy meters_update_manager on public.meters for update to authenticated using (exists(select 1 from public.units u where u.id=unit_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[]))) with check (exists(select 1 from public.units u where u.id=unit_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[])));
drop policy meters_delete_admin on public.meters;
create policy meters_delete_admin on public.meters for delete to authenticated using (exists(select 1 from public.units u where u.id=unit_id and private.has_org_role(u.organization_id,array['owner','admin']::public.organization_role[])));
drop policy energy_readings_select_member on public.energy_readings;
create policy energy_readings_select_member on public.energy_readings for select to authenticated using (exists(select 1 from public.meters m join public.units u on u.id=m.unit_id where m.id=meter_id and private.is_org_member(u.organization_id)));
drop policy energy_readings_insert_manager on public.energy_readings;
create policy energy_readings_insert_manager on public.energy_readings for insert to authenticated with check (exists(select 1 from public.meters m join public.units u on u.id=m.unit_id where m.id=meter_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[])));
drop policy energy_readings_update_manager on public.energy_readings;
create policy energy_readings_update_manager on public.energy_readings for update to authenticated using (exists(select 1 from public.meters m join public.units u on u.id=m.unit_id where m.id=meter_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[]))) with check (exists(select 1 from public.meters m join public.units u on u.id=m.unit_id where m.id=meter_id and private.has_org_role(u.organization_id,array['owner','admin','manager']::public.organization_role[])));
drop policy energy_readings_delete_admin on public.energy_readings;
create policy energy_readings_delete_admin on public.energy_readings for delete to authenticated using (exists(select 1 from public.meters m join public.units u on u.id=m.unit_id where m.id=meter_id and private.has_org_role(u.organization_id,array['owner','admin']::public.organization_role[])));
drop policy alerts_select_member on public.alerts;
create policy alerts_select_member on public.alerts for select to authenticated using (private.is_org_member(organization_id));
drop policy alerts_update_member on public.alerts;
create policy alerts_update_member on public.alerts for update to authenticated using (private.is_org_member(organization_id)) with check (private.is_org_member(organization_id));
drop function public.is_org_member(uuid);
drop function public.has_org_role(uuid,public.organization_role[]);
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
create or replace function public.create_organization(p_name text,p_legal_name text default null) returns public.organizations language plpgsql security invoker set search_path=public as $$ declare new_org public.organizations; current_user_id uuid := (select auth.uid()); begin if current_user_id is null then raise exception 'authentication required'; end if; if nullif(trim(p_name),'') is null then raise exception 'organization name is required'; end if; insert into public.organizations(name,legal_name) values(trim(p_name),nullif(trim(p_legal_name),'')) returning * into new_org; insert into public.organization_members(organization_id,user_id,role) values(new_org.id,current_user_id,'owner'); return new_org; end; $$;
revoke execute on function public.create_organization(text,text) from public,anon;
grant execute on function public.create_organization(text,text) to authenticated;
